### ISSUE TITLE
feat: choose a date for the meeting

### ISSUE THREAD

**Issue by dmcclccam** [unbankedpag/meet#2]
## TODOS
- [ ] Add date picker
- [ ] Integrate with calendars (google/outlook)
- [ ] Generate `.ics` attachment
